version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: georuby
    versions:
    - "> 2.0.0"
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: webpacker
    versions:
    - 5.2.2
  - dependency-name: rails
    versions:
    - 5.2.4.5
    - 5.2.5
  - dependency-name: rubocop
    versions:
    - 1.12.0
  - dependency-name: webmock
    versions:
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: skylight
    versions:
    - 5.0.0
  - dependency-name: geocoder
    versions:
    - 1.6.5
  - dependency-name: i18n-js
    versions:
    - 3.8.1
  - dependency-name: codecov
    versions:
    - 0.4.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: marked
    versions:
    - 1.2.9
    - 2.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
