# Start with Spotifys style guide as a base then customize from there
inherit_from:
  - .rubocop_shopify_styleguide.yml
  - .rubocop_todo.yml

# Apply rule to all cops
AllCops:
  Include:
    - '*/**/*.rb'
    - '/Rakefile'
    - '/config.ru'
  Exclude:
    - 'vendor/*'
    - 'bin/*'
    - 'doc/*'
    - 'log/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'test/**/*'
    - 'public/**/*'
    - 'Dangerfile'
  TargetRubyVersion: '2.4'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Max: 303
