version: "2"
services:
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=plots
      - MYSQL_USER=plots
      - MYSQL_PASSWORD=plots
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ../config/my.cnf:/etc/mysql/my.cnf
      # for configuration 
      - ../../mysql:/var/lib/mysql
      # for persistence
      - ../../dump:/docker-entrypoint-initdb.d
      # for importing a dump
      # if you want to re-import simply put away ../../mysql/*
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server
  web:
    build: ..
    command: /bin/bash -c "sleep 5 && bundle exec rails s -p 5001 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ..:/app
    ports: 
      - "127.0.0.1:5001:5001"
    links:
      - db
    restart: unless-stopped
  sidekiq:
    build: ..
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
