OAUTH_GOOGLE_APP_KEY: "199741036945-28ir745pk5veim1t69j53le689pvsldb"
OAUTH_GOOGLE_APP_SECRET: "gtMWQhWg7ND1xUYUHxTncs_f"
OAUTH_GITHUB_APP_KEY: b68deb1d7d598d8a0c42
OAUTH_GITHUB_APP_SECRET: fb5c6b3a4c3d428c34e5d59cc6e40ceb7f6811be
OAUTH_TWITTER_APP_KEY: H59J9kJBVQvtZvWhr2SUAht4o
OAUTH_TWITTER_APP_SECRET:  GEQOygPITjGj2Imzg5ALJeCqE0GdQU2GAmTYOS9kEPcLVlMxQu
OAUTH_FACEBOOK_APP_KEY: "1725277740901299"
OAUTH_FACEBOOK_APP_SECRET: "8e8a054996bc6c9f870d2ffb4e4cc014"
