defaults: &defaults
  # If using the asset pipeline, provide the manifest name
  manifest_name: application
  # Else provide the relative path of your CSS file from the /public directory
  # css_path: /path/to/css/from/public/main.css
  # Or provide a separate path for each route
  # css_paths:
  #   - /path/to/css/from/public/main.css
  routes:
    - /

development:
  <<: *defaults
  base_url: http://localhost:3000

staging:
  <<: *defaults
  base_url: http://stable.publiclab.org

production:
  <<: *defaults
  base_url: http://publiclab.org
