#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.logger = Logger.new("log/mailman.log")

# Email Configration for mailman
Mailman.config.pop3 = {
  server: 'pop.example.com', 
  port: 995, 
  ssl: true,
  username: 'ENV[USERNAME]',
  password: 'ENV[EMAIL_PASSWORD]'
}

Mailman::Application.run do
  # routes are written here
  # route for mail having node with id in their subject will only be accepted for processing
  default do
  	begin
      Comment.receive_mail(message)
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end

end
