# .dependabot/config.yml
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
